const MARKDOWN_PROVIDER_KEY = Symbol('vue-element-plus-x-markdown-provider');

const SHIKI_CACHE_KEY_LENGTH = 10000;
const MERMAID_CACHE_KEY_LENGTH = 10000;

export {
  MARKDOWN_PROVIDER_KEY,
  MERMAID_CACHE_KEY_LENGTH,
  SHIKI_CACHE_KEY_LENGTH
};
